PY=python

run:
	$(PY) driftlock_sim/sims/run_single.py --config driftlock_sim/configs/demo_movie.yaml

sweep:
	$(PY) driftlock_sim/sims/run_sweep.py --config driftlock_sim/configs/sweep_small.yaml

movie:
	$(PY) driftlock_sim/sims/make_movie.py --config driftlock_sim/configs/demo_movie.yaml

